struct ibuf *init_ibuf(size_t s);
struct obuf *init_obuf(size_t s);
void free_ibuf(struct ibuf *b);
void free_obuf(struct obuf *b);
int unget_ch(struct ibuf *b, char ch);
int put_ch(struct obuf *b, char ch);
int unget_str(struct ibuf *b, const char *str);
int unget_file(struct ibuf *b, const char *fn);
int get_ch(struct ibuf *input, char *ch, int read_stdin);
int get_word(struct ibuf *input, struct obuf *token, int read_stdin);
int eat_whitespace(struct ibuf *input, int read_stdin);
int delete_to_nl(struct ibuf *input, int read_stdin);
int put_str(struct obuf *b, const char *str);
int put_obuf(struct obuf *b, struct obuf *t);
int put_file(struct obuf *b, const char *fn);
int write_obuf(struct obuf *b, const char *fn);
int flush_obuf(struct obuf *b);
struct lbuf *init_lbuf(size_t n);
void free_lbuf(struct lbuf *b);
int add_l(struct lbuf *b, long x);
